# Allows hydra to open up in the original folder of the run
defaults:
  - paths: default.yaml
  - hydra: default.yaml
  - _self_

# The name of the model to export
project_name: nu2flows
network_name: test
batch_size: 1024
samples_per_event: 1024
