_target_: src.datamodules.dilepton.H5DataModule

train_conf:
  data_dir: ${paths.data_dir}
  met_kins: px,py
  lep_kins: px,py,pz,log_energy
  jet_kins: px,py,pz,log_energy
  nu_kins: px,py,pz
  file_list:
  - train.h5

valid_conf:
  data_dir: ${paths.data_dir}
  met_kins: ${..train_conf.met_kins}
  lep_kins: ${..train_conf.lep_kins}
  jet_kins: ${..train_conf.jet_kins}
  nu_kins: ${..train_conf.nu_kins}
  file_list:
  - val.h5

test_conf:
  data_dir: ${paths.data_dir}
  met_kins: ${..train_conf.met_kins}
  lep_kins: ${..train_conf.lep_kins}
  jet_kins: ${..train_conf.jet_kins}
  nu_kins: ${..train_conf.nu_kins}
  file_list:
  - test.h5

loader_conf:
  pin_memory: True
  batch_size: 4096
  num_workers: 0
